// Copyright (c) 2026 Zwelithini Ngomane (cypriel17@gmail.com). All rights reserved.
// Enterprize360 HR & Payroll Management System
// Unauthorised copying, distribution or modification is strictly prohibited.

// Auto-generated by set-env.js — do not edit manually.
export const environment = {
  production: true,
  apiUrl: 'https://crm-production.up.railway.app'
};
