// Copyright (c) 2026 Zwelithini Ngomane (cypriel17@gmail.com). All rights reserved.
// LKCentrix HR & Payroll Management System — ORION
// Unauthorised copying, distribution or modification is strictly prohibited.

// Auto-generated by set-env.js — do not edit manually.
export const environment = {
  production: true,
  apiUrl: 'https://orion-payroll-api.onrender.com'
};
