/**
 * Runs before `ng build --configuration production` on Vercel.
 * Reads the API_URL environment variable and writes it into
 * environment.prod.ts so Angular bakes the correct URL into the bundle.
 *
 * Set API_URL in Vercel → Project → Settings → Environment Variables
 * e.g.  API_URL = https://orion-payroll-api.onrender.com
 */
const { writeFileSync } = require('fs');
const { join } = require('path');

const apiUrl = process.env.API_URL || '';

const content = `// Auto-generated by set-env.js — do not edit manually.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}'
};
`;

const targetPath = join(__dirname, 'environment.prod.ts');
writeFileSync(targetPath, content, { encoding: 'utf8' });
console.log(`[set-env] environment.prod.ts written — apiUrl: "${apiUrl}"`);
