/**
 * Runs before `ng build --configuration production` in the Docker build.
 * Reads the API_URL environment variable and writes it into
 * environment.prod.ts so Angular bakes the correct URL into the bundle.
 *
 * Set API_URL as a Railway build-arg/service variable for the
 * enterprize360-app service, e.g.
 * API_URL = https://enterprize360-api-production.up.railway.app
 */
const { writeFileSync } = require('fs');
const { join } = require('path');

const apiUrl = process.env.API_URL || 'https://enterprize360-api-production.up.railway.app';

const content = `// Auto-generated by set-env.js — do not edit manually.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}'
};
`;

const targetPath = join(__dirname, 'environment.prod.ts');
writeFileSync(targetPath, content, { encoding: 'utf8' });
console.log(`[set-env] environment.prod.ts written — apiUrl: "${apiUrl}"`);
